version: '3.2'
services:
  db: 
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=db_passmanager
      - MYSQL_USER=lokesh
      - MYSQL_PASSWORD=lokesh
      - MYSQL_ROOT_PASSWORD=lokesh
    # ports:
    #   - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
      
  web:
    image: pm
    # command: python manage.py makemigrations
    # command: python manage.py migrate
    command: python manage.py runserver 0:8000
    depends_on:
      - db
    environment:
      - APP_MODULE=attendance_api.asgi:application
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=lokesh
      - DB_PASSWORD=lokesh
      - DB_NAME=db_passmanager
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  
  

volumes:
  mysql_db:
    driver: local
